spring:
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
app:
  jwt:
    refresh-token-cookie-secure: ${JWT_REFRESH_COOKIE_SECURE:false}
logging:
  level:
    root: INFO
